### PR TITLE
Make OpaqueIpcReceiver useful

### PR DESCRIPTION
**Pull request by Manishearth**
Currently it can't be converted to an IpcReceiver and isn't serializable, which makes it rather useless.

r? @pcwalton

### CODE REVIEW

**Comment by pcwalton** [comment]
I'm somewhat uncomfortable reviewing this, because I don't recall the design constraints of `OpaqueIpcReceiver` anymore.

**Comment by Manishearth** [comment]
cc @antrik

**Comment by antrik** [comment]
I'm not sure I can help much with this: I never worked much with that part of of the code base. There may or may not have been a time where I fully understood the idea behind `OpaqueIpcSender` and `OpaqueIpcReceiver` -- but if there was, that's been a while ago...

As far as I can tell, the proposed change simply brings `OpaqueIpcReceiver` in line with `OpaqueIpcSender`? While that seems reasonable on the surface, I really can't tell whether there was some rationale why it hasn't been like that from the beginning...

What's the use case, anyway?

One thing I can say though is that `OpaqueIpcReceiver` is being used in `router.rs` -- so it's certainly not "useless" as is...

**Comment by jdm** [comment]
#250 will need to merge before this one can.

**Comment by oli-cosmian** [comment]
Could someone publish a new version with this change included?

**Comment by jdm** [comment]
Opened https://github.com/servo/ipc-channel/pull/253 to start the process.

**Comment by Manishearth** [comment]
This seems to already be included? https://docs.rs/ipc-channel/0.13.0/ipc_channel/ipc/struct.OpaqueIpcReceiver.html

**Comment by oli-cosmian** [comment]
I just was confused. This PR was merged after `Cargo.toml` was last changed. Sorry for the noise

**Pull request merged**
