### PR TITLE
Update crossbeam to 0.7 and crossbeam-channel to 0.4

### PR DESCRIPTION
**Pull request by mbrobbel**

### CODE REVIEW

**Comment by nox** [comment]
(Note that this is a breaking change, we may want to lay down the upgrade path of ipc-channel in servo first.)

**Comment by atouchet** [comment]
Note: There is another PR with similar changes as well #247

**Comment by Eijebong** [comment]
Woops, hadn't seen this one... Mine doesn't break benchmarks though :p

**Comment by nox** [comment]
Duplicate of #247.

**Pull request closed without merging**
