### PR TITLE
Don't set SO_RCVBUF on UNIX sockets.

### PR DESCRIPTION
**Pull request by eddyb**
Fixes servo/servo#10260, although this might not be even a reasonable approach.
At this point it's mostly guesswork and Servo needs a lot more testing on linux.

### CODE REVIEW

**Comment by pcwalton** [comment]
Bluh?

I mean, r=me I guess, but this is kinda scary…

**Comment by samlh** [comment]
Pure speculation: if there are multiple senders, then perhaps the receive buffer needs to be large enough to receive from all simultaneously?

**Comment by eddyb** [comment]
Closed in favor of #60.

**Pull request closed without merging**
