### PR TITLE
Fix notification handling tests and `unix` implementation

### PR DESCRIPTION
**Pull request by antrik**
The first commit attempts to make notification tests more robust. (Hopefully fixing intermittent failures on Linux.) The other commits add some additional related tests, and fix a (minor) issue uncovered by them.

### CODE REVIEW

**Comment by metajack** [comment]
Are there no other solutions? Sleeps feel like a bit of a hack.

**Comment by antrik** [comment]
@metajack my assumption was that if it's a thread scheduling issue, a sleep of any duration should make it reliable, as it explicitly hands off scheduling... But it seems my assumption was wrong, as the sleep didn't fix the intermittents.

I have implemented polling in a loop now instead -- let's hope this works better.

In order to verify that the loop indeed handles delayed notifications, I added separate tests forcing a delay -- and uncovered an actual issue in the notification handling on Linux in the process... So the PR grew in scope :-)

**Comment by jdm** [comment]
One of the TravisCI jobs seems displeased: https://travis-ci.org/servo/ipc-channel/jobs/385864860

**Pull request merged**
