### PR TITLE
Bump version to 0.1.1

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
@metajack Should that be bumped to 1.0 directly?

**Comment by Ms2ger** [comment]
I think we should

**Comment by nox** [comment]
And we should clean `Cargo.toml` too, then:

```
unused manifest key: dependencies.serde.opt_level
```

**Comment by Ms2ger** [comment]
We're using this from git still, so no real reason to keep this PR until we move to crates.io.

**Pull request closed without merging**
