### PR TITLE
Fix IpcOneShotServer for `inprocess` backend

### PR DESCRIPTION
**Pull request by antrik**
Several patches covering individual aspects, each fixing one possible situation that was broken.

(I don't think there was actually *any* situation that was working correctly before...)

### CODE REVIEW

**Comment by antrik** [comment]
I tested this by forcing the `inprocess` backend on GNU/Linux -- let's see whether it actually works on Windows as well...

**Comment by jdm** [comment]
```
---- platform::test::server_no_accept stdout ----

	thread 'platform::test::server_no_accept' panicked at 'assertion failed: pingback_rx.try_recv().is_err()', platform/test.rs:426

note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:

    platform::test::server_no_accept
```

**Comment by jdm** [comment]
Looks like the test failure happens on mac.

**Comment by antrik** [comment]
Actually, I am surprised that it didn't fail on the GNU/Linux builder: it turns out this test case fails on my system when using the Linux backend. (I forgot to try that before...)

It seems I made a wrong assumption about how `connect()` behaves on sockets, and consequently how it's supposed to behave in `ipc-channel`. I'll rework the series to account for that.

**Comment by antrik** [comment]
Looks better now.

I also implemented an alternate approach, using a `Drop` trait for cleanup: https://github.com/antrik/ipc-channel/commit/3d1e1401f908c805fee0c7b5b5fbae033a6e2ca0 I'd say it is more elegant -- but I'm not entirely sure it's a good idea, because of the locking involved... Opinions?

**Comment by pcwalton** [comment]
Looks good once conflicts are resolved. Sorry about the delay!

**Comment by emilio** [comment]
Rebased in #100,

Thanks, @antrik! :)

**Pull request closed without merging**
