### PR TITLE
Update windows-rs to 0.58

### LINKED ISSUE #345: Update windows-rs
Latest version is 0.58, we use 0.48.

### PR DESCRIPTION
**Pull request by sagudev**
Fix #345.

My first time working with windows-rs, so review carefully. I tried to stick to the current code schematic, but the whole codebase  would need a cleanup (a lot of clippy warnings).

Draft because I want a companion PR in servo.

### CODE REVIEW

**Comment by atouchet** [comment]
Servo now has windows 0.58 in its dependencies. Does this still need to remain a draft?

**Comment by sagudev** [comment]
> Servo now has windows 0.58 in its dependencies. Does this still need to remain a draft?

Not really, I just forgot.

**Review by mrobinson — APPROVED** [review]
I am by no means an expert in the Win32 API, but looked over this a couple times and I don't see any obvious issues. If it works, I say let's go for it.

**Comment by sagudev** [comment]
> I am by no means an expert in the Win32 API, but looked over this a couple times and I don't see any obvious issues. If it works, I say let's go for it.

The problem is that even that if it does not works the bugs are subtile (most changes are in error handling which happens rarely, and we only run smoketest for win, we need windows-wpt).

**Pull request merged**
