### PR TITLE
macOS: Don't leak disconnected senders

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by pcwalton** [comment]
Could you add a comment explaining why we use `mach_port_deallocate()` instead of `mach_port_mod_refs()`? This is subtle.

**Comment by jdm** [comment]
The commit message includes the explanation; should I duplicate it in code comments?

**Comment by pcwalton** [comment]
@jdm Probably a good idea, yeah. I'm worried someone will modify this code and reintroduce the bug.

**Pull request merged**
