### PR TITLE
Turn on `SO_LINGER` for client communication sockets.

### LINKED ISSUE #29: Intermittent "Connection reset by peer" for in-process channel in a recv() with a queued message but no sender
We got a panic in this code in Servo:

```
226                 Command::Exit(result) => {
227                     result.send(()).unwrap();
228                     break;
229                 }
...
382     pub fn exit(&self) {
383         let (response_chan, response_port) = ipc::channel().unwrap();
384         self.chan.send(Command::Exit(response_chan)).unwrap();
385         response_port.recv().unwrap();
386     }
```
The panic:
```
  │ thread 'Constellation' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 104, message: "Connection reset by peer" } }', ../src/libcore/result.rs:688
```
This is on Linux.

### PR DESCRIPTION
**Pull request by pcwalton**
This reduces the probability that the receiver receives errors when we
close our end of the socket with data remaining.

There is deadlock potential with this patch, because turning on `SO_LINGER`
causes `close()` to block until the receiver has received all the data. If
deadlocks happen, a workaround will be to close sockets in a separate thread.
This is ugly and slow, so I don't want to do that unless we need to.

Might fix #29.

r? @jdm

### CODE REVIEW

**Comment by jdm** [comment]
This means that the socket hangs around for 30s before its data becomes unavailable like before, right?

**Comment by pcwalton** [comment]
It's 30 seconds or whenever the receiver has read all the data, whichever comes first. The 30 second timeout should hopefully never happen in practice--it would only happen if the receiver leaked its receiving end for some reason.

**Comment by jdm** [comment]
Well, it's not hard for me to imagine cases where the receiver is not sitting waiting synchronously and is occasionally polling (the equivalent of setTimeout, basically), but this seems like it should be an improvement over the status quo.

**Comment by jdm** [comment]
Will need to wait for either https://github.com/Manishearth/rust-clippy/issues/576 or https://github.com/serde-rs/aster/issues/63.

**Comment by jdm** [comment]
```
platform/linux/mod.rs:499:18: 499:24 error: `linger` does not name a structure [E0422]

platform/linux/mod.rs:499     let linger = linger {

                                           ^~~~~~

platform/linux/mod.rs:499:18: 499:24 help: run `rustc --explain E0422` to see a detailed explanation

platform/linux/mod.rs:504:32: 504:42 error: unresolved name `SOL_SOCKET` [E0425]

platform/linux/mod.rs:504                                SOL_SOCKET,

                                                         ^~~~~~~~~~

platform/linux/mod.rs:504:32: 504:42 help: run `rustc --explain E0425` to see a detailed explanation

platform/linux/mod.rs:506:50: 506:56 error: use of undeclared type name `linger` [E0412]

platform/linux/mod.rs:506                                &linger as *const linger as *const c_void,

                                                                           ^~~~~~

platform/linux/mod.rs:506:50: 506:56 help: run `rustc --explain E0412` to see a detailed explanation

platform/linux/mod.rs:507:47: 507:53 error: use of undeclared type name `linger` [E0412]

platform/linux/mod.rs:507                                mem::size_of::<linger>() as socklen_t);

                                                                        ^~~~~~

platform/linux/mod.rs:507:47: 507:53 help: run `rustc --explain E0412` to see a detailed explanation

platform/linux/mod.rs:499:18: 499:24 error: `linger` does not name a structure [E0422]

platform/linux/mod.rs:499     let linger = linger {

                                           ^~~~~~

platform/linux/mod.rs:499:18: 499:24 help: run `rustc --explain E0422` to see a detailed explanation

platform/linux/mod.rs:504:32: 504:42 error: unresolved name `SOL_SOCKET` [E0425]

platform/linux/mod.rs:504                                SOL_SOCKET,

                                                         ^~~~~~~~~~

platform/linux/mod.rs:504:32: 504:42 help: run `rustc --explain E0425` to see a detailed explanation

platform/linux/mod.rs:506:50: 506:56 error: use of undeclared type name `linger` [E0412]

platform/linux/mod.rs:506                                &linger as *const linger as *const c_void,

                                                                           ^~~~~~

platform/linux/mod.rs:506:50: 506:56 help: run `rustc --explain E0412` to see a detailed explanation

platform/linux/mod.rs:507:47: 507:53 error: use of undeclared type name `linger` [E0412]

platform/linux/mod.rs:507                                mem::size_of::<linger>() as socklen_t);

                                                                        ^~~~~~
```
Incomplete changes?

**Comment by pcwalton** [comment]
Forgot to commit changes. r? @jdm

**Pull request merged**
