### PR TITLE
Use get_max_fragment_size for medium_data tests

### PR DESCRIPTION
**Pull request by sunshowers**
Currently, the `medium_data` tests all hang on illumos because (a) we first send a message and then receive it on the same thread, and (b) the tests fill up the pipe buffer before the send is complete. That's because illumos uses a smaller buffer size than other platforms like Linux.

The goal of these tests is to test situations where fragmentation doesn't happen, so use `get_max_fragment_size` which shouldn't fill up the pipe buffer under ordinary circumstances.

(There are other tests which check for fragmentation, so that code path is still covered.)

It would also be nice to move all of the receives to other threads in the future, but this appears to work quite well.

See #101.

### CODE REVIEW

**Review by jdm — APPROVED** [review]
This looks like a reasonable improvement!

**Comment by jdm** [comment]
Oh, lol—for the macOS implementation the max fragment size is usize::MAX, so that's why we're seeing `capacity overflow` panics in CI.

**Comment by sunshowers** [comment]
> Oh, lol—for the macOS implementation the max fragment size is usize::MAX, so that's why we're seeing `capacity overflow` panics in CI.

Ah I guess that's because the macOS impl uses Mach ports. I'll set a cap on the fragment size used, thanks.

**Comment by sunshowers** [comment]
Updated! Capped it at the previously-used 64KiB value.

**Comment by sagudev** [comment]
Are we sure we need to change these values? I think you need to make sure that fragmentation works on illumos: https://github.com/servo/ipc-channel/blob/4e51f9505bc91cb04409b2eea59ba829b212cf91/src/platform/test.rs#L224-L229

**Comment by sunshowers** [comment]
> Are we sure we need to change these values? I think you need to make sure that fragmentation works on illumos: 

The huge_data tests do exercise that, but good point about those specific tests -- will enable that.

**Comment by sunshowers** [comment]
I've updated the PR summary to indicate what's happening.

**Comment by sunshowers** [comment]
Also enabled the fragment tests on illumos.

**Comment by sunshowers** [comment]
Hi — is there any way I can help get this landed? Thanks!

**Review by mrobinson — APPROVED** [review]

**Comment by mrobinson** [comment]
Apologies for the wait and thanks for the fix. This looks good to me!

**Pull request merged**
