### PR TITLE
Update serde to 0.9

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
Blocked on https://github.com/rust-lang-nursery/uuid/pull/80 and https://github.com/TyOverby/bincode/issues/106.

**Comment by jdm** [comment]
We have a couple problems that need to be resolved before we can upgrade the version of ipc-channel that Servo uses:
* https://github.com/servo/ipc-channel/pull/119
* https://github.com/servo/ipc-channel/issues/131

**Comment by nox** [comment]
@jdm Who can work on that?

**Comment by antrik** [comment]
@nox please don't post major changes as edits: GitHub doesn't send a new notification for that.

 The fix for https://github.com/servo/ipc-channel/issues/131 in https://github.com/servo/ipc-channel/pull/137 is indeed almost done; but https://github.com/servo/ipc-channel/pull/119 is stalled... On a follow-up from @jdm in fact. Though at this point I have half a mind to just merge it regardless.

**Comment by nox** [comment]
@bors-servo retry

Don't disappoint me Travis

**Comment by nox** [comment]
Larsborsing this.

Linux: https://travis-ci.org/servo/ipc-channel/builds/202716464

macOS:

```
[nox:~/src/ipc-channel] serde
± cargo build --features unstable
   Compiling ipc-channel v0.7.0 (file:///Users/nox/src/ipc-channel)
    Finished dev [unoptimized + debuginfo] target(s) in 3.63 secs

[nox:~/src/ipc-channel] serde 3s
± cargo test --features unstable
   Compiling ipc-channel v0.7.0 (file:///Users/nox/src/ipc-channel)
    Finished dev [unoptimized + debuginfo] target(s) in 8.3 secs
     Running target/debug/deps/ipc_channel-d70b1b46b61ae1e9

running 58 tests
test platform::test::big_data ... ok
test platform::test::big_data_with_0_fds ... ok
test platform::test::big_data_with_5_fds ... ok
test platform::test::big_data_with_2_fds ... ok
test platform::test::big_data_with_4_fds ... ok
test platform::test::cross_process_sender_transfer ... ok
test platform::test::cross_process ... ok
test platform::test::fd_only ... ignored
test platform::test::big_data_with_1_fds ... ok
test platform::test::multisender_transfer ... ok
test platform::test::big_data_with_6_fds ... ok
test platform::test::no_senders_notification ... ok
test platform::test::receiver_set ... ok
test platform::test::empty ... ok
test platform::test::receiver_set_close_after_adding ... ok
test platform::test::big_data_with_3_fds ... ok
test platform::test::receiver_set_close_before_adding ... ok
test platform::test::medium_data ... ok
test platform::test::medium_data_with_sender_transfer ... ok
test platform::test::receiver_set_empty ... ok
test platform::test::receiver_transfer ... ok
test platform::test::sender_transfer ... ok
test platform::test::receiver_set_concurrent ... ok
test platform::test::receiver_set_medium_data ... ok
test platform::test::server_accept_first ... ok
test platform::test::simple ... ok
test platform::test::server_connect_first ... ok
test platform::test::receiver_set_eintr ... ok
test platform::test::sync_test::receiver_not_sync ... ok
test platform::test::try_recv ... ok
test platform::test::shared_memory_clone ... ok
test test::bytes ... ok
test test::embedded_bytes_receivers ... ok
test test::cross_process_embedded_senders ... ok
test test::embedded_opaque_senders ... ok
test test::embedded_receivers ... ok
test test::embedded_senders ... ok
test test::multiple_paths_to_a_sender ... ok
test test::opaque_sender ... ok
test test::router_drops_callbacks_on_cloned_sender_shutdown ... ok
test test::router_drops_callbacks_on_sender_shutdown ... ok
test platform::test::shared_memory ... ok
test test::router_multiplexing ... ok
test test::router_routing_to_new_mpsc_receiver ... ok
test test::router_multithreaded_multiplexing ... ok
test test::router_simple ... ok
test test::select ... ok
test test::simple ... ok
test test::test_reentrant ... ok
test test::test_so_linger ... ok
test test::try_recv ... ok
test platform::test::big_data_with_sender_transfer ... ok
test platform::test::receiver_set_big_data ... ok
test test::shared_memory ... ok
test platform::test::try_recv_large ... ok
test platform::test::concurrent_senders ... ok
test test::router_big_data ... ok
test platform::test::try_recv_large_delayed ... ok

test result: ok. 57 passed; 0 failed; 1 ignored; 0 measured

   Doc-tests ipc-channel

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


[nox:~/src/ipc-channel] serde 10s
± cargo build --features "unstable force-inprocess"
   Compiling ipc-channel v0.7.0 (file:///Users/nox/src/ipc-channel)
    Finished dev [unoptimized + debuginfo] target(s) in 2.77 secs

[nox:~/src/ipc-channel] serde 3s
± cargo test --features "unstable force-inprocess"
   Compiling ipc-channel v0.7.0 (file:///Users/nox/src/ipc-channel)
    Finished dev [unoptimized + debuginfo] target(s) in 7.46 secs
     Running target/debug/deps/ipc_channel-527c65fbf394bb4c

running 53 tests
test platform::test::big_data ... ok
test platform::test::big_data_with_3_fds ... ok
test platform::test::big_data_with_4_fds ... ok
test platform::test::big_data_with_6_fds ... ok
test platform::test::big_data_with_1_fds ... ok
test platform::test::big_data_with_2_fds ... ok
test platform::test::big_data_with_0_fds ... ok
test platform::test::empty ... ok
test platform::test::big_data_with_5_fds ... ok
test platform::test::multisender_transfer ... ok
test platform::test::no_senders_notification ... ok
test platform::test::receiver_set ... ok
test platform::test::fd_only ... ok
test platform::test::receiver_set_close_after_adding ... ok
test platform::test::receiver_set_close_before_adding ... ok
test platform::test::medium_data ... ok
test platform::test::receiver_set_empty ... ok
test platform::test::medium_data_with_sender_transfer ... ok
test platform::test::receiver_transfer ... ok
test platform::test::sender_transfer ... ok
test platform::test::receiver_set_concurrent ... ok
test platform::test::receiver_set_medium_data ... ok
test platform::test::simple ... ok
test platform::test::sync_test::receiver_not_sync ... ok
test platform::test::try_recv ... ok
test platform::test::server_connect_first ... ok
test test::bytes ... ok
test test::embedded_bytes_receivers ... ok
test test::embedded_opaque_senders ... ok
test test::embedded_receivers ... ok
test test::embedded_senders ... ok
test test::multiple_paths_to_a_sender ... ok
test test::opaque_sender ... ok
test platform::test::shared_memory_clone ... ok
test test::router_drops_callbacks_on_cloned_sender_shutdown ... ok
test test::router_drops_callbacks_on_sender_shutdown ... ok
test test::router_multiplexing ... ok
test test::router_multithreaded_multiplexing ... ok
test test::router_routing_to_new_mpsc_receiver ... ok
test test::router_simple ... ok
test test::select ... ok
test platform::test::shared_memory ... ok
test test::simple ... ok
test test::test_reentrant ... ok
test test::test_so_linger ... ok
test test::try_recv ... ok
test platform::test::big_data_with_sender_transfer ... ok
test test::shared_memory ... ok
test platform::test::receiver_set_big_data ... ok
test platform::test::try_recv_large ... ok
test platform::test::concurrent_senders ... ok
test test::router_big_data ... ok
test platform::test::try_recv_large_delayed ... ok

test result: ok. 53 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests ipc-channel

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Pull request merged**
