### PR TITLE
Update mio.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
https://github.com/carllerche/mio/commit/43a69f218957ea7f43bb821734dbfbad09078c6b, https://github.com/carllerche/mio/commit/32f34cdcfe7a6e13e4101afe4cb6e66bcde90a80, https://github.com/carllerche/mio/commit/607fb5466ed6d846b866d6c7da6fb54f3382c118, https://github.com/carllerche/mio/commit/c8312b719bb4d640806d8bbbd00e258df955e647, and https://github.com/carllerche/mio/commit/ef182bae193a9c7457cd2cf661fcaffb226e3eef look like commits that could have an impact on our Linux implementation. I want to see if these improve https://github.com/servo/servo/issues/16154 at all.

**Comment by antrik** [comment]
@jdm I'm a bit confused: why do you need to update the version requirement in `ipc-channel` for that?

(BTW, I personally prefer doing the version bump in the same commit that introduces the change prompting the bump...)

**Comment by antrik** [comment]
On an unrelated note, what's up with highfive? That's the second time it failed to assign a reviewer...

**Comment by jdm** [comment]
I've always assumed that sometimes highfive runs afoul of github's API request limit.

**Comment by jdm** [comment]
Also this PR is not necessary to try out changes to mio in Servo. I thought it was.

**Pull request closed without merging**
