### PR TITLE
platform/test: More test cases for receiver sets etc.

### PR DESCRIPTION
**Pull request by antrik**
This adds a bunch of new test cases improving coverage for
`OsIpcReceiverSet`; along with a pair of tests for sending empty
messages in general, which wasn't covered before at all.

### CODE REVIEW

**Comment by antrik** [comment]
This is mostly to establish a baseline for https://github.com/servo/ipc-channel/pull/123

**Comment by antrik** [comment]
Oh, now *that's* an interesting catch... Though not exactly what I was after ;-)

**Comment by antrik** [comment]
I disabled the failing test on MacOS, since it can be argued that it doesn't expose a user-visible bug... Though the failure is still suspicious.

**Comment by emilio** [comment]
Sounds good to me. Sorry this took so long to get reviewed @antrik, feel free to ping me if it happens again. I don't feel I have the time to do all the reviews I should in ipc-channel, but I'll try to find/bug an appropriate reviewer when possible.

Thanks again!

@bors-servo r+

**Comment by antrik** [comment]
@emilio thanks :-)

I wish this repository had highfive, or some other measures to make sure PRs are taken care of... I hate having to prod people all the time; and I find the difficulty of landing things in `ipc-channel` sometimes quite demotivating :-(

**Comment by fitzgen** [comment]
> I wish this repository had highfive, or some other measures to make sure PRs are taken care of... I hate having to prod people all the time; and I find the difficulty of landing things in ipc-channel sometimes quite demotivating :-(

What is needed to get high five enabled for this repo? What you describe is a situation we absolutely shouldn't be in.

**Comment by fitzgen** [comment]
https://github.com/servo/highfive/#enabling-a-repo has steps to enable, although I don't have admin rights for this repo.

**Comment by metajack** [comment]
Highfive webhook has now been added to this repo.

**Pull request merged**
