### PR TITLE
platform/tests: cleanup: drop `truncate()` calls on received data

### PR DESCRIPTION
**Pull request by antrik**
I really can't think of any purpose these might serve...

### CODE REVIEW

**Comment by emilio** [comment]
Looking at the [output of the build](https://travis-ci.org/servo/ipc-channel/jobs/134534644), it seems `truncate()` makes a difference on OSX.

**Comment by antrik** [comment]
Interesting... Let me check something.

**Comment by antrik** [comment]
Yeah, guessed so... So normally it doesn't matter that the `macos` backend introduces trailing zeros, as they are simply ignored during deserialisation; but with `bytes_channel`, this is now exposed to the public...

Now let's try another thing...

**Comment by antrik** [comment]
Meh. No idea how to fix this.

**Comment by emilio** [comment]
@antrik: I'm closing this since it seems inactive. Feel free to reopen if you find a solution :/

**Comment by antrik** [comment]
Heh, funny timing: I wanted to close it myself right now, as not being an Apple worshipper err I mean developer, there is nothing I can do about this...

I opened a bug report instead ( https://github.com/servo/ipc-channel/issues/83 ), for someone else to take care of.

**Pull request closed without merging**
