### PR TITLE
[WIP] Add native Windows back-end

### PR DESCRIPTION
**Pull request by antrik**
This picks up from https://github.com/servo/ipc-channel/pull/108

For now, it's just commit refactoring (squashing/splitting) of the original PR -- though the intention is to add a series of follow-up commits next, doing some improvements to the actual code, according to my latest review of the original PR.

Since the implementation is essentially working at this point though, it could also be merged as is, if that turns out necessary.

### CODE REVIEW

**Comment by antrik** [comment]
Note: the Linux test failure is a known intermittent in the test condition (happening under memory pressure), not in the actual `ipc-channel` implementation -- it is on my list to fix when I get around to it...

**Comment by antrik** [comment]
Dropped `truncate()` calls from the newly introduced tests -- missed that during the rebase...

**Comment by nox** [comment]
What's the status on this?

**Comment by antrik** [comment]
@nox every time I get to work on the issues I already know, I find other bits to improve as well... So it's hard to give an estimate. If I don't run into any serious problems, it could be done in a few days -- but I wouldn't count on that...

**Comment by nox** [comment]
No problem @antrik, was just doing a bit of triaging.

**Comment by reset** [comment]
@antrik we'd love a separate windows-stable branch (if this is it, that's ok too) for the Habitat project to consume. We can provide any feedback you need and have a team of Rust programmers ourselves if you need any help. Thanks so much for all the hard work here!

**Comment by antrik** [comment]
@reset I realised that maintaining a "stable" branch will only be easy if I can still rewrite history at will like in the WIP branch... I can add a tag however every time I update it, so you would still have persistent reference points. (Though no proper bisecting between them...) Would that work for you?

**Comment by reset** [comment]
@antrik rewriting history is actually just fine by us! If the branch is rebased against master in a regular enough cadence then we can just add this branch as the source for the cargo dep

**Comment by antrik** [comment]
@reset this doesn't sound like a good idea to me... I'm not sure what exactly it implies to add a branch as the source of a cargo dep -- but it sounds bad in either case: if it means cargo always fetches the actual current state of the branch at build time, that would open the possibility of your build changing or even breaking due to changes in an external repository -- which is kinda against the whole idea of cargo... If on the other hand it means cargo registers the specific commit the branch points to at the time `cargo update` is run, that wouldn't work either, since after pushing a new history for the branch, the previous commits are gone from the repository...

The tags on the other wouldn't change once created; and they would make sure the commits stay around even when the branch changes.

**Comment by reset** [comment]
@antrik right, since you're rewriting history the commit hash will change. A tag would be perfect :)

**Comment by antrik** [comment]
@reset just to be clear: if cargo registers the specific commit (hash) on `cargo update`, it should still be fine to point it to the branch, as long as I remember to add a tag each time I publish, so the commits don't go away later :-)

**Comment by antrik** [comment]
I pushed the first version of the "stable" branch to https://github.com/antrik/ipc-channel/tree/windows-stable ( https://github.com/antrik/ipc-channel.git ), along with tag https://github.com/antrik/ipc-channel/tree/0.8.0_windows1 ( https://github.com/antrik/ipc-channel.git ). Let's hope I didn't break anything yet :-)

I also created a pseudo-PR from that branch at https://github.com/servo/ipc-channel/pull/169 , mostly to have confirmation that the things I push to that branch actually work...

**Comment by reset** [comment]
@antrik I'll test the branch out in a build tonight and get back. Super appreciate it!

**Comment by nox** [comment]
Maintaining a tag for something that is a work in progress sounds like a very bad idea to me.

**Comment by antrik** [comment]
@nox there might be a misunderstanding here: my intention is to create a dedicated tag for every new "stable" snapshot.

**Comment by nox** [comment]
> @nox there might be a misunderstanding here: my intention is to create a dedicated tag for every new "stable" snapshot.

This is what I understood. Tags stay forever. I guess that's fine as long as these tags don't leave your fork.

**Comment by reset** [comment]
@nox you can purge tags on a remote with `git push <remote> :<tag>`. Is there another more permanent thing you're talking about in your dev/release process?

**Comment by antrik** [comment]
So I finally managed to work through all the comments I made on the latest version of the original PR (plus a bunch of others I found along the way...) -- however, in the process I also discovered a pretty fundamental issue with the buffer handling, breaking the contract associated with `unsafe` code blocks... So I still don't really feel comfortable merging this as is :-( However, the fix will be rather invasive, and I'm not sure how long it will take...

For now, I pushed a new version to the `windows-stable` branch, tagged with `0.8.0_windows2`.

**Comment by jdm** [comment]
Thanks for continuing to look into this @antrik!

**Comment by reset** [comment]
@antrik thanks for the update and all the hard work!

**Comment by antrik** [comment]
A little belatedly, I pushed another update to `windows-stable` (tag `0.9.0_windows1`), syncing with the 0.9 master release. (Along with some further refactoring I did in the Windows back-end.)

I had hoped it might end up not being necessary, if I managed to wrap up my rework fast enough... But it turned out to be even more of a rabbit hole than I anticipated.

(On the plus side, I *think* I have a workable design now that I can finish implementing...)

**Comment by retep998** [comment]
>But it turned out to be even more of a rabbit hole than I anticipated.

Dang humans always trying to get in my hole...

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by antrik** [comment]
@Boscop well, the truth is, while working on the big refactor to isolate unsafety, I got stuck on a design choice a couple months ago that I couldn't decide on for a while, and got distracted... I only resumed working on this recently.

There is good news though. For one, I finally learned how to compile-check for a different target, which makes working on this a *lot* easier. (It's trivial actually: just install the target rustlibs, and then `cargo check --target i686-pc-windows-msvc`... Not sure why I didn't realise this before.)

More importantly, I made progress with the refactoring -- for the first time I feel that I'm actually nearing the end...

...though that actually doesn't matter all that much any more: I figured out a way to isolate the unsafety *without* needing much refactoring after all!

I think the refactoring will still be useful, putting all the related unsafe code in one place -- but with the actual unsafety leaking no longer an issue, the refactoring doesn't need to land in the initial PR.

There are still a couple of things I want to wrap up; but nothing very tricky any more I believe :-)

**Comment by ebkalderon** [comment]
Anyone know the current status of this PR? Is no one working on it anymore?

**Comment by SamuelMarks** [comment]
How's this progressing?

**Comment by ofek** [comment]
Any update?

**Comment by jdm** [comment]
#233 has the latest updates.

**Comment by jdm** [comment]
Fixed in #272

**Comment by SamuelMarks** [comment]
Great to see @jdm

PS: Might be worth updating the top-level README.md for this repo also

**Pull request closed without merging**
